// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using MovieTime.Web.Movie.Persistance;

namespace MovieTime.Web.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20180305020002_MovieGenreRelationship")]
    partial class MovieGenreRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieTime.Web.Entities.DbGenre", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("CustomField");

                    b.HasKey("Name");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MovieTime.Web.Entities.DbMovieGenre", b =>
                {
                    b.Property<Guid>("DbMovieId");

                    b.Property<string>("DbGenreId");

                    b.HasKey("DbMovieId", "DbGenreId");

                    b.HasIndex("DbGenreId");

                    b.ToTable("MovieGenre");
                });

            modelBuilder.Entity("MovieTime.Web.MovieDetails.DbMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Actors")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("ImdbId");

                    b.Property<string>("Plot")
                        .IsRequired()
                        .HasMaxLength(600);

                    b.Property<string>("Poster")
                        .IsRequired();

                    b.Property<double>("Rated");

                    b.Property<int>("RunTimeInMinutes")
                        .HasMaxLength(1440);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("Year");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieTime.Web.Entities.DbMovieGenre", b =>
                {
                    b.HasOne("MovieTime.Web.Entities.DbGenre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("DbGenreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MovieTime.Web.MovieDetails.DbMovie", "Movie")
                        .WithMany("Genres")
                        .HasForeignKey("DbMovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
